
server:
  port: 8081

spring:
  application:
    name: techworkshop-schnittstelle
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: development

allergen:
  locale: de_DE

---

# Spring

spring:
  profiles: development
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      port: 27017
      database: techworkshop-schnittstelle

---

# Spring

spring:
  profiles: test
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      port: 27017
      database: techworkshop-schnittstelle-test