
server:
  port: 8085

spring:
  application:
    name: techworkshop-schnittstelle
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: development

allergen:
  locale: de_DE

---

# Spring

spring:
  profiles: development
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: techworkshop-schnittstelle
      uri: mongodb+srv://MongoUser:mongotest@cluster0.i0lyi.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

---

# Spring

spring:
  profiles: test
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: techworkshop-schnittstelle-test
      uri: mongodb+srv://MongoUser:mongotest@cluster0.i0lyi.mongodb.net/myFirstDatabase?retryWrites=true&w=majority