server:
  port: 8082

spring:
  application:
    name: techworkshop-mongo
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: development

allergen:
  locale: de_DE

---

# Spring

spring:
  profiles: development
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://MongoUser:mongotest@cluster0.i0lyi.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: techworkshop-mongo-develop

---

# Spring

spring:
  profiles: test
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://MongoUser:mongotest@cluster0.i0lyi.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: techworkshop-mongo-test